/** Aliases dos endpoints `api_publica_{sigla}` (DataJud / CNJ). Lista enxuta — expanda conforme necessidade. */
export const DATAJUD_TRIBUNAIS: { sigla: string; nome: string }[] = [
  { sigla: 'tjsp', nome: 'TJ — São Paulo' },
  { sigla: 'tjrj', nome: 'TJ — Rio de Janeiro' },
  { sigla: 'tjmg', nome: 'TJ — Minas Gerais' },
  { sigla: 'tjprs', nome: 'TJ — Rio Grande do Sul' },
  { sigla: 'tjba', nome: 'TJ — Bahia' },
  { sigla: 'tjsc', nome: 'TJ — Santa Catarina' },
  { sigla: 'tjpr', nome: 'TJ — Paraná' },
  { sigla: 'tjce', nome: 'TJ — Ceará' },
  { sigla: 'tjpe', nome: 'TJ — Pernambuco' },
  { sigla: 'tjgo', nome: 'TJ — Goiás' },
  { sigla: 'tjdft', nome: 'TJ — Distrito Federal' },
  { sigla: 'tjes', nome: 'TJ — Espírito Santo' },
  { sigla: 'tjma', nome: 'TJ — Maranhão' },
  { sigla: 'tjms', nome: 'TJ — Mato Grosso do Sul' },
  { sigla: 'tjmt', nome: 'TJ — Mato Grosso' },
  { sigla: 'tjpa', nome: 'TJ — Pará' },
  { sigla: 'tjpb', nome: 'TJ — Paraíba' },
  { sigla: 'tjpi', nome: 'TJ — Piauí' },
  { sigla: 'tjal', nome: 'TJ — Alagoas' },
  { sigla: 'tjam', nome: 'TJ — Amazonas' },
  { sigla: 'tjap', nome: 'TJ — Amapá' },
  { sigla: 'tjrn', nome: 'TJ — Rio Grande do Norte' },
  { sigla: 'tjse', nome: 'TJ — Sergipe' },
  { sigla: 'tjro', nome: 'TJ — Rondônia' },
  { sigla: 'tjrr', nome: 'TJ — Roraima' },
  { sigla: 'tjto', nome: 'TJ — Tocantins' },
  { sigla: 'tjac', nome: 'TJ — Acre' },
  { sigla: 'trf1', nome: 'TRF — 1ª Região' },
  { sigla: 'trf2', nome: 'TRF — 2ª Região' },
  { sigla: 'trf3', nome: 'TRF — 3ª Região' },
  { sigla: 'trf4', nome: 'TRF — 4ª Região' },
  { sigla: 'trf5', nome: 'TRF — 5ª Região' },
  { sigla: 'trf6', nome: 'TRF — 6ª Região' },
  { sigla: 'trt1', nome: 'TRT — 1ª Região (RJ)' },
  { sigla: 'trt2', nome: 'TRT — 2ª Região (SP)' },
  { sigla: 'trt3', nome: 'TRT — 3ª Região (MG)' },
  { sigla: 'trt15', nome: 'TRT — 15ª Região (SP campinas)' },
  { sigla: 'tst', nome: 'TST' },
  { sigla: 'stj', nome: 'STJ' },
  { sigla: 'stm', nome: 'STM' },
]
